// Generates contracts/src/insa/TalArt.sol from talArt.ts: node src/nft/talSol.ts
import { writeFileSync } from "node:fs";
import { BACKDROPS, CHARMS, DEFS, GRAIN, HEADWEAR, LIFT, MASKS, PALETTES, SHADOW, UNREVEALED, WOODS } from "./talArt.ts";

const lit = (s: string) => {
  if (/['\\\n]/.test(s)) throw new Error(`unsafe literal: ${s.slice(0, 40)}`);
  return `'${s}'`;
};
const chain = (fn: string, xs: string[], ret = "string memory") => {
  const body = xs.map((x, i) => `        ${i ? "else " : ""}if (i == ${i}) return ${lit(x)};`).join("\n");
  return `    function ${fn}(uint256 i) internal pure returns (${ret}) {\n${body}\n        return "";\n    }\n`;
};
const weights = (name: string, t: { weight: number }[]) => `    uint256 internal constant ${name}_TOTAL = ${t.reduce((a, x) => a + x.weight, 0)};\n`;
const cum = (fn: string, t: { weight: number }[]) => {
  let acc = 0;
  const lines = t.map((x, i) => {
    acc += x.weight;
    return `        if (x < ${acc}) return ${i};`;
  });
  return `    function ${fn}(uint256 x) internal pure returns (uint8) {\n${lines.join("\n")}\n        return ${t.length - 1};\n    }\n`;
};

const src = `// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

// GENERATED by ops/src/nft/talSol.ts from ops/src/nft/talArt.ts. Do not edit by hand.

/// @title TalArt — the drawing tables of 탈 Tal, Jangteo's on-chain mask collection.
contract TalArt {
${weights("BACKDROP", BACKDROPS)}${weights("PALETTE", PALETTES)}${weights("WOOD", WOODS)}${weights("MASK", MASKS)}${weights("HEADWEAR", HEADWEAR)}${weights("CHARM", CHARMS)}
    /// @notice Trait indexes: backdrop, palette, wood, mask, headwear, charm.
    function traits(uint256 seed, uint256 id) public pure returns (uint8[6] memory t) {
        uint256 r = uint256(keccak256(abi.encode(seed, id)));
        t[0] = _backdropAt((r & 0xffff) % BACKDROP_TOTAL);
        t[1] = _paletteAt(((r >> 16) & 0xffff) % PALETTE_TOTAL);
        t[2] = _woodAt(((r >> 32) & 0xffff) % WOOD_TOTAL);
        t[3] = _maskAt(((r >> 48) & 0xffff) % MASK_TOTAL);
        t[4] = _headwearAt(((r >> 64) & 0xffff) % HEADWEAR_TOTAL);
        t[5] = _charmAt(((r >> 80) & 0xffff) % CHARM_TOTAL);
    }

    function svg(uint8[6] memory t) public pure returns (string memory) {
        return string.concat(
            string.concat('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 400">', ${lit(DEFS)}, _style(t[1], t[2]), _backdrop(t[0])),
            string.concat(${lit(LIFT)}, ${lit(SHADOW)}, _mask(t[3]), _headwear(t[4]), '</g>', _charm(t[5]), ${lit(GRAIN)}, '</svg>')
        );
    }

    function unrevealed() public pure returns (string memory) {
        return ${lit(UNREVEALED)};
    }

    /// @notice English trait names, for metadata: kind 0 backdrop, 1 palette, 2 wood, 3 mask, 4 headwear, 5 charm.
    function traitName(uint256 kind, uint256 i) public pure returns (string memory) {
        if (kind == 0) return _backdropName(i);
        if (kind == 1) return _paletteName(i);
        if (kind == 2) return _woodName(i);
        if (kind == 3) return _maskName(i);
        if (kind == 4) return _headwearName(i);
        return _charmName(i);
    }

    function _style(uint8 p, uint8 w) internal pure returns (string memory) {
        (string memory b, string memory b2, string memory b3) = _palette(p);
        (string memory f, string memory fs, string memory f1, string memory l) = _wood(w);
        return string.concat(
            string.concat('<style>.b{fill:', b, '}.b2{fill:', b2, '}.b3{fill:', b3, '}.b2s{stroke:', b2, '}.b3s{stroke:', b3, '}'),
            string.concat('.fc{fill:url(#w);stroke:', l, ';stroke-opacity:.3;stroke-width:2}.fs{fill:', fs, '}.f1{stop-color:', f1, '}.f2{stop-color:', f, '}.f3{stop-color:', fs, '}'),
            string.concat('.e{fill:', l, '}.ls{stroke:', l, '}.s{fill:none;stroke:', l, ';stroke-width:4;stroke-linecap:round;stroke-linejoin:round}'),
            '.h{fill:#1d1a18}.r{fill:#b3312a}.rs{stroke:#b3312a}.w{fill:#f4ecdc}.g{fill:#d9a93c}.k{fill:#191716}.k2{fill:#6b5a3a}.k2s{stroke:#3b2f22}</style>'
        );
    }

    function _palette(uint256 i) internal pure returns (string memory, string memory, string memory) {
${PALETTES.map((p, i) => `        if (i == ${i}) return (${lit(p.b)}, ${lit(p.b2)}, ${lit(p.b3)});`).join("\n")}
        return ("", "", "");
    }

    function _wood(uint256 i) internal pure returns (string memory, string memory, string memory, string memory) {
${WOODS.map((w, i) => `        if (i == ${i}) return (${lit(w.f)}, ${lit(w.fs)}, ${lit(w.f1)}, ${lit(w.l)});`).join("\n")}
        return ("", "", "", "");
    }

${cum("_backdropAt", BACKDROPS)}${cum("_paletteAt", PALETTES)}${cum("_woodAt", WOODS)}${cum("_maskAt", MASKS)}${cum("_headwearAt", HEADWEAR)}${cum("_charmAt", CHARMS)}
${chain("_backdrop", BACKDROPS.map((x) => x.svg))}${chain("_mask", MASKS.map((x) => x.svg))}${chain("_headwear", HEADWEAR.map((x) => x.svg))}${chain("_charm", CHARMS.map((x) => x.svg))}
${chain("_backdropName", BACKDROPS.map((x) => x.name))}${chain("_paletteName", PALETTES.map((x) => x.name))}${chain("_woodName", WOODS.map((x) => x.name))}${chain("_maskName", MASKS.map((x) => x.name))}${chain("_headwearName", HEADWEAR.map((x) => x.name))}${chain("_charmName", CHARMS.map((x) => x.name))}}
`;
writeFileSync(new URL("../../../contracts/src/insa/TalArt.sol", import.meta.url), src);
console.log("TalArt.sol written");
